# Mathematics Essential

## Practicals

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from scipy import special

%matplotlib inline

In [2]:
A = np.random.rand(3, 5)
print(f'A:\n {A}')
B = np.random.rand(5, 3)
print(f'B:\n {B}')

A:
 [[2.32097658e-01 8.69667156e-01 4.84704212e-01 5.25999376e-01
  4.91347784e-01]
 [2.68178184e-01 4.94268659e-01 1.06246931e-01 3.53954676e-01
  2.60253588e-01]
 [4.63476477e-01 7.08619753e-01 5.11177454e-01 5.06374713e-04
  3.28189071e-01]]
B:
 [[0.91514208 0.92206441 0.50696091]
 [0.54801509 0.04371969 0.07101968]
 [0.05481562 0.12848639 0.14812604]
 [0.46152671 0.1618032  0.98097817]
 [0.23866374 0.99569726 0.92332776]]


### <span style="color:red">=========== Assignment 1 ===========</span>

In [3]:
print(np.cov(A))
print(np.cov(B))

[[0.05181368 0.02135129 0.02134169]
 [0.02135129 0.0201814  0.00443371]
 [0.02134169 0.00443371 0.06908979]]
[[ 0.05649512  0.02997956 -0.00762168 -0.09235792 -0.04069762]
 [ 0.02997956  0.08043063 -0.01352072 -0.01237722 -0.11838764]
 [-0.00762168 -0.01352072  0.00241999  0.00707961  0.01970604]
 [-0.09235792 -0.01237722  0.00707961  0.17178527  0.01157761]
 [-0.04069762 -0.11838764  0.01970604  0.01157761  0.17451699]]


### <span style="color:red">=========== End of Assignment 1 ===========</span>

### <span style="color:red">=========== Assignment 2 ===========</span> 

In [4]:
wA, vA = np.linalg.eig(np.cov(A))
print(wA)
print(vA)

[0.0873713  0.04489887 0.00881469]
[[-0.60187996 -0.63480495  0.48452368]
 [-0.24149236 -0.43363999 -0.86812315]
 [-0.76119771  0.63951469 -0.10769867]]


In [27]:
wB, vB = np.linalg.eig(np.cov(B))
print(wB)
print(vB)

[0.00000000e+00 1.99003025e-01 2.86644970e-01 1.45857798e-17
 7.55788750e-19]
[[ 0.87767663 -0.32649542 -0.35083396 -0.35523744  0.85975886]
 [-0.0876903   0.27672108 -0.47689766  0.79244098 -0.17778532]
 [ 0.02778817 -0.02204063  0.09002889 -0.01540209 -0.1463089 ]
 [ 0.45687615  0.7892349   0.40847798 -0.16475853  0.45097583]
 [ 0.11174137 -0.439828    0.68885753  0.46739818  0.06649494]]


### <span style="color:red">=========== End of Assignment 2 ===========</span>

### <span style="color:red">=========== Assignment 3 ===========</span>

In [ ]:
X = vB * wB
X = np.dot(X, np.matrix(vB).I)
X

Matrix x is the same as matrix cov(B) 

### <span style="color:red">=========== End of Assignment 3 ===========</span>

### <span style="color:red">=========== Assignment 4 ===========</span>

In [ ]:
A_svd = np.linalg.svd(A)
B_svd = np.linalg.svd(B)
A_svd

In [ ]:
B_svd

### <span style="color:red">=========== End of Assignment 4 ===========</span>

### <span style="color:red">=========== Assignment 5 ===========</span>

In [ ]:
ratio = []
for d in range(1, 21):
    ratio.append((np.pi ** (d/2)) / (d*2 ** (d-1) * special.gamma(d/2)))

plt.plot(range(1,21), ratio)
plt.xlabel('dimensions')
plt.ylabel('ratio')

### <span style="color:red">=========== End of Assignment 5 ===========</span>

## Mathematics

### <span style="color:red">=========== Assignment 6 ===========</span>



[Answer]

### <span style="color:red">=========== End of Assignment 6 ===========</span>


### <span style="color:red">=========== Assignment 7 ===========</span>

[Answer]

### <span style="color:red">=========== End of Assignment 7 ===========</span>

### <span style="color:red">=========== Assignment 8 ===========</span>

[Answer]

### <span style="color:red">=========== End of Assignment 8 ===========</span>

### <span style="color:red">=========== Assignment 9 ===========</span>

[Answer]

### <span style="color:red">=========== End of Assignment 9 ===========</span>